const os = require('node:os')

console.log('Información del sistema operativo: ')
console.log('------------------------')
console.log('Nombre', os.platform())
console.log('Versión', os.release())
console.log('Arquitectura', os.arch())
console.log('CPUs', os.cpus())
console.log('Ram Libre', os.freemem() / 1024 / 1024)
console.log('Ram Total', os.totalmem() / 1024 / 1024)
console.log('uptime', os.uptime() / 60 / 60)
