---
version: '3.8'
services:
  django:
    build:
      target: production
    image: django-prod-${PROJECT_NAME}
    container_name: django-prod-${PROJECT_NAME}
    environment:
      DD_DATABASE_NAME: ${DD_DATABASE_NAME}
    depends_on:
      - mysql
  mysql:
    container_name: mysql-prod-${PROJECT_NAME}
    environment:
      MYSQL_DATABASE: ${DD_DATABASE_NAME}
    volumes:
      - prod_data:/var/lib/mysql
volumes:
  prod_data: {}
