---
version: '3.8'
services:
  django:
    build:
      context: ../
      dockerfile: ./docker/dockerfiles/dockerfile.django
      target: base
    image: django-base-${PROJECT_NAME}
    container_name: django-base-${PROJECT_NAME}
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      DD_DATABASE_USER: ${DD_DATABASE_USER}
      DD_DATABASE_HOST: ${DD_DATABASE_HOST}
      DD_DATABASE_PASSWORD: ${DD_DATABASE_PASSWORD}
      DD_DATABASE_DIALECT: ${DD_DATABASE_DIALECT}
    depends_on:
      - mysql
    ports:
      - target: 3000
        published: ${DD_PORT:-3000}
        protocol: tcp
        mode: host
  mysql:
    image: mysql:8.0
    container_name: mysql-base-${PROJECT_NAME}
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${DD_DATABASE_USER}
      MYSQL_PASSWORD: ${DD_DATABASE_PASSWORD}
      DD_DATABASE_DIALECT: ${DD_DATABASE_DIALECT}
    command:
      [
        'mysqld',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci'
      ]
