### Recuperar información del pokemon ditto
GET http://localhost:1234/pokemon/ditto
### Para crear un Pokemon
POST http://localhost:1234/pokemon/ditto
Content-Type: application/json
    
    {
        "name": "pikachu",
        "type": "electric",
        "moves": [
            "thunderbolt", 
            "quick attack"
            ]
    }   
